language: generic
udo: required
services:
    - docker

before_install:
    - docker build -t asiorgad/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true asiorgad/react-test npm test


after_success:
    - docker build -t asiorgad/multi-client ./client
    - docker build -t asiorgad/multi-nginx ./nginx
    - docker build -t asiorgad/multi-server ./server
    - docker build -t asiorgad/multi-worker ./worker
    
    - echo "$DOCKER_PASSWORD" | docker login - "$DOCKER_ID" --password-stdin

    - docker push asiorgad/multi-client
    - docker push asiorgad/multi-nginx
    - docker push asiorgad/multi-server
    - docker push asiorgad/multi-worker

    



